{% set data = load_setup_py_data() %}

package:
  name: vlutils
  version: {{ data.get('version') }}

source:
  path: ../

requirements:
  build:
    - python
    - setuptools

  run:
    - python>=3.9
    - pytorch>=1.7
    - tqdm
    - rich
    - pynvml

build:
  noarch: python
  number: 271

about:
  home: https://github.com/cfm-uestc/vlutils
  license: Apache-2.0
  summary: VL-Group Utilities
