package:
  name: vlutils
  version: {{ environ.get('PKG_VERSION', '') }}

source:
  path: ../

requirements:
  build:
    - python
    - setuptools

  host:
    - python>=3.9
    - pytorch>=1.7
    - tqdm
    - rich

about:
  home: https://github.com/cfm-uestc/vlutils
  license: Apache-2.0
  summary: VL-Group Utilities
